// Resizes the raw photos in public/images/ to web-sized WebP and writes a
// typed manifest with blur placeholders. Run manually: npm run photos
import sharp from "sharp";
import { readdir, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const SRC = "public/images";
const OUT = "public/images/web";
const MANIFEST = "src/data/photos.ts";
const LONG_EDGE = 1600;

await mkdir(OUT, { recursive: true });
const files = (await readdir(SRC)).filter((f) => /\.(jpe?g|png)$/i.test(f)).sort();
if (files.length === 0) {
  console.error(`No source photos found in ${SRC}`);
  process.exit(1);
}

const entries = [];
for (const file of files) {
  const name = path.parse(file).name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  const img = sharp(path.join(SRC, file)).rotate(); // respect EXIF orientation
  const outName = `${name}.webp`;
  const info = await img
    .clone()
    .resize({ width: LONG_EDGE, height: LONG_EDGE, fit: "inside", withoutEnlargement: true })
    .webp({ quality: 78 })
    .toFile(path.join(OUT, outName));
  const blur = await img.clone().resize({ width: 24 }).webp({ quality: 40 }).toBuffer();
  entries.push({
    src: `/images/web/${outName}`,
    width: info.width,
    height: info.height,
    blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
  });
  console.log(`${file} -> ${outName} (${info.width}x${info.height}, ${Math.round(info.size / 1024)}KB)`);
}

const ts = `// Generated by scripts/prepare-photos.mjs — do not edit by hand.
export type Photo = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const PHOTOS: Photo[] = ${JSON.stringify(entries, null, 2)};
`;
await writeFile(MANIFEST, ts);
console.log(`Wrote ${entries.length} entries to ${MANIFEST}`);
