// Generated by scripts/prepare-photos.mjs — do not edit by hand.
export type Photo = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const PHOTOS: Photo[] = [
  {
    "src": "/images/web/9q5a8160.webp",
    "width": 1600,
    "height": 1067,
    "blurDataURL": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAAAwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZACw7Yyoe2BH+xpGrWaxNwAA4AZoMH7W+PykW8eatMC2QhNH7tdvdy2tVnPs/b2mjUQ3TgB3nhom76dQ6ZEM/nuNhrRnXs+LNrcIe2b/8Zz/TbJfGdrtFDdTbIUP1srDUokal+xSlzMBsZ37HWYlkkABC9yPFw2KeqF3N0ByoH/IqCvoCgCMrZ+l9EAA"
  },
  {
    "src": "/images/web/9q5a8162.webp",
    "width": 1600,
    "height": 1067,
    "blurDataURL": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAACQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZACdAdwAlP/AzX0BFMepRu7RoOAAy/cvauwsPg7pF+8tNIRV6jfHuZtx3/xILPmGhQfYq3J47AyHuA2v0ryznA5tX87M87IwuMr4Q6imj3ymLv1V4bLZr/ahuE4T11anA/J9oR9FYjvYA6sCgawwE7B23fVnlx/5QAAA"
  },
  {
    "src": "/images/web/9q5a8164.webp",
    "width": 1600,
    "height": 1067,
    "blurDataURL": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZACdABM8rXfCvaY48ozragAAyQcWDwff9V1NqQAp0CyFf5UPQumeum4/VNcZ8AvESjNJLLEyPlnPn6al9hUxLP1eBkgLcSfKEfstPzY6VrXeA7aYD7lsOVW7WLVJ0aEvAT4a8B/GkYBpJ+fnD3lUtdWiAsgfPZO7Zq34jzlRVdAA"
  },
  {
    "src": "/images/web/9q5a8165.webp",
    "width": 1600,
    "height": 1067,
    "blurDataURL": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZgCdAy6AspKREn7OhasPoADdUlmVWldtR/tWTodrl/jZQFb00zBPcI/20o6qeod/gs/3Ft5R3waf/FzFYNuxor2r/lwWBja523PlXK3t+5yg/zq2fDxiDpHEvxsgToPtYCWuTu7bQq0F5jbMykgfxB1Wl88qG90D6MeeCuAAAA=="
  },
  {
    "src": "/images/web/9q5a8166.webp",
    "width": 1600,
    "height": 1067,
    "blurDataURL": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZACdABK5U8PEk2tjqOvJcADbjK8NekS6ZBTr6IxsRBWdSa3sI94MYUScKcGp+j19wnVZJLOpMbQzIirHEDWviTfTO83sF009DXwsaMTp2+hfPSmwGHJkSz0SO5s3N2dHO7nkmfDJ9SCSGj7q7X938JUnC7/F5LkQ8voMQoTeuBBuQQAAAA=="
  }
];
